# Generated by Django 5.0.6 on 2026-07-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_article_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('category_confidence', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('sentiment_compound', models.FloatField(blank=True, null=True)),
                ('language_code', models.CharField(blank=True, default='en', max_length=10)),
                ('language_name', models.CharField(blank=True, default='English', max_length=50)),
                ('translated_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('entities_json', models.JSONField(blank=True, default=list)),
                ('topic_id', models.IntegerField(blank=True, null=True)),
                ('insight', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=500)),
                ('detected_intent', models.CharField(blank=True, max_length=50)),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('n_results', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
